const references = {
    "01_hol08": {
        "ccs":"Human-centered Computing",
        "title": "Organic user interfaces: designing computers in any way, shape, or form.",
        "year": 2008,
        "scores": [5, 5, 5],
        "category": "Top-rated",
        "keyword": "NUI",
        "section": "David Holman and Roel Vertegaal. 2008. Organic user interfaces: designing computers in any way, shape, or form. Commun. ACM 51, 6 (June 2008), 48-55. DOI:https://doi.org/10.1145/1349026.1349037",
    }, 
    "02_ono11": {
        "ccs":"Applied Computing",
        "title": "Space art: aesthetics design as psychological support.",
        "year": 2011,
        "scores": [5, 5, 5],
        "category": "Top-rated",
        "keyword": "NUI",
        "section": "Ayako Ono and Irene Lia Schlacht. 2011. Space art: aesthetics design as psychological support. Personal Ubiquitous Comput. 15, 5 (June 2011), 511-518. DOI:https://doi.org/10.1007/s00779-010-0325-5",
    },
    "03_bow12": {
        "ccs":"Computing Methodologies",
        "title": "Questioning naturalism in 3D user interfaces.",
        "year": 2012,
        "scores": [5, 5, 5],
        "category": "Top-rated",
        "keyword": "NUI",
        "section": "Doug A. Bowman, Ryan P. McMahan, and Eric D. Ragan. 2012. Questioning naturalism in 3D user interfaces. Commun. ACM 55, 9 (September 2012), 78-88. DOI:https://doi.org/10.1145/2330667.2330687",

    },
    "04_sch11": {
        "ccs":"General and Reference",
        "title": "Space design.",
        "year": 2011,
        "scores": [4, 5, 5],
        "category": "Top-rated",
        "keyword": "NUI",
        "section": "Irene Lia Schlacht and Henrik Birke. 2011. Space design. Personal Ubiquitous Comput. 15, 5 (June 2011), 497-509. DOI:https://doi.org/10.1007/s00779-010-0326-4",

    },
    "05_bay19": {
        "ccs":"Human-centered Computing",
        "title": "The Design of Social Drones: A Review of Studies on Autonomous Flyers in Inhabited Environments.",
        "year": 2019,
        "scores": [5, 4, 5],
        "category": "Top-rated",
        "keyword": "Natural Interaction",
        "section": "Mehmet Aydin Baytas, Damla Cay, Yuchong Zhang, Mohammad Obaid, Asim Evren Yantac, and Morten Fjeld. 2019. The Design of Social Drones: A Review of Studies on Autonomous Flyers in Inhabited Environments. In Proceedings of the 2019 CHI Conference on Human Factors in Computing Systems (CHI‚ 2019). Association for Computing Machinery, New York, NY, USA, Paper 250, 1-13. DOI:https://doi.org/10.1145/3290605.3300480",
    }, 
    "06_san04": {
        "ccs":"Computing Methodologies",
        "title": "Multi-Agent Patrolling with Reinforcement Learning.",
        "year": 2004,
        "scores": [5, 4, 4],
        "category": "Top-rated",
        "keyword": "Computation",
        "section": "Hugo Santana, Geber Ramalho, Vincent Corruble, and Bohdana Ratitch. 2004. Multi-Agent Patrolling with Reinforcement Learning. In Proceedings of the Third International Joint Conference on Autonomous Agents and Multiagent Systems - Volume 3 (AAMAS ‚2004). IEEE Computer Society, USA, 1122-1129.",
    },
    "07_nie90": {
        "ccs":"Software and its Engineering",
        "title": "Traditional dialogue design applied to modern user interfaces.",
        "year": 1990,
        "scores": [3, 5, 5],
        "category": "Top-rated",
        "keyword": "NUI",
        "section": "Jakob Nielsen. 1990. Traditional dialogue design applied to modern user interfaces. Commun. ACM 33, 10 (October 1990), 109-118. DOI:https://doi.org/10.1145/84537.84559",

    },
    "08_sar10": {
        "ccs":"Human-centered Computing",
        "title": "Bimanual handheld mixed reality interfaces for urban planning.",
        "year": 2010,
        "scores": [3, 5, 5],
        "category": "Top-rated",
        "keyword": "Natural Interaction",
        "section": "Markus Sareika and Dieter Schmalstieg. 2010. Bimanual handheld mixed reality interfaces for urban planning. In Proceedings of the International Conference on Advanced Visual Interfaces (AVI ‚2010). Association for Computing Machinery, New York, NY, USA, 189-196. DOI:https://doi.org/10.1145/1842993.1843027",

    },
    "09_wei11": {
        "ccs":"Information Systems",
        "title": "PaperSketch: a paper-digital collaborative remote sketching tool.",
        "year": 2011,
        "scores": [3, 5, 5],
        "category": "Top-rated",
        "keyword": "Natural Interaction",
        "section": "Nadir Weibel, Beat Signer, Moira C. Norrie, Hermann Hofstetter, Hans-Christian Jetter, and Harald Reiterer. 2011. PaperSketch: a paper-digital collaborative remote sketching tool. In Proceedings of the 16th international conference on Intelligent user interfaces (IUI ’11). Association for Computing Machinery, New York, NY, USA, 155–164. DOI:https://doi.org/10.1145/1943403.1943428",
    },
    "10_gra19": {
        "ccs":"Theory of Computation",
        "title": "Optimal Budget-Feasible Mechanisms for Additive Valuations.",
        "year": 2019,
        "scores": [5, 4, 4],
        "category": "Top-rated",
        "keyword": "Computation",
        "section": "Nick Gravin, Yaonan Jin, Pinyan Lu, and Chenhao Zhang. 2019. Optimal Budget-Feasible Mechanisms for Additive Valuations. In Proceedings of the 2019 ACM Conference on Economics and Computation (EC ‚2019). Association for Computing Machinery, New York, NY, USA, 887-900. DOI:https://doi.org/10.1145/3328526.3329586",
    },
    "11_ume11": {
        "ccs":"Computing Methodologies",
        "title": "Sensitive couture for interactive garment modeling and editing.",
        "year": 2011,
        "scores": [3, 5, 4],
        "category": "Top-rated",
        "keyword": "Natural Interaction",
        "section": "Nobuyuki Umetani, Danny M. Kaufman, Takeo Igarashi, and Eitan Grinspun. 2011. Sensitive couture for interactive garment modeling and editing. ACM Trans. Graph. 30, 4, Article 90 (July 2011), 12 pages. DOI:https://doi.org/10.1145/2010324.1964985",
    },
    "12_xin08": {
        "ccs":"Human-centered Computing",
        "title": "Napkin sketch: handheld mixed reality 3D sketching.",
        "year": 2008,
        "scores": [3, 5, 4],
        "category": "Top-rated",
        "keyword": "Natural Interaction",
        "section": "Min Xin, Ehud Sharlin, and Mario Costa Sousa. 2008. Napkin sketch: handheld mixed reality 3D sketching. In Proceedings of the 2008 ACM symposium on Virtual reality software and technology (VRST ‚2008). Association for Computing Machinery, New York, NY, USA, 223-226. DOI:https://doi.org/10.1145/1450579.1450627",
    },
    "13_jeo11": {
        "ccs":"Human-centered Computing",
        "title": "Spindex (Speech Index) Improves Auditory Menu Acceptance and Navigation Performance.",
        "year": 2011,
        "scores": [3, 5, 4],
        "category": "Top-rated",
        "keyword": "Natural Interaction",
        "section": "Jeon, Myounghoon, and Bruce N. Walker. 2011. “Spindex (Speech Index) Improves Auditory Menu Acceptance and Navigation Performance.” https://doi.org/10.1145/1952383.1952385.",
    },
    "14_jeo12": {
        "ccs":"Human-centered Computing",
        "title": "“Spindex” (Speech Index) Enhances Menus on Touch Screen Devices with Tapping, Wheeling, and Flicking.",
        "year": 2012,
        "scores": [3, 5, 4],
        "category": "Top-rated",
        "keyword": "Natural Interaction",
        "section": "Jeon, M., Walker, B. N., & Srivastava, A. (2012). “Spindex” (Speech Index) Enhances Menus on Touch Screen Devices with Tapping, Wheeling, and Flicking. ACM Trans. Comput.-Hum. Interact., 19(2), 1–27. https://doi.org/10.1145/2240156.2240162",
    },
    "15_hay08": {
        "ccs":"Human-centered Computing",
        "title": "Creating Effective Decision Aids for Complex Tasks.",
        "year": 2008,
        "scores": [5, 3, 3],
        "category": "Top-rated",
        "keyword": "Natural Interaction",
        "section": "Hayes, Caroline C., and Farnaz Akhavi. 2008. “Creating Effective Decision Aids for Complex Tasks.” https://conservancy.umn.edu/handle/11299/110038.",
    },
    "16_nen16": {
        "ccs":"Software and its Engineering",
        "title": "SCORE: Exploiting Global Broadcasts to Create Offline Personal Channels for On-Demand Access.",
        "year": 2016,
        "scores": [5, 2, 4],
        "category": "Top-rated",
        "keyword": "Computation",
        "section": "Gianfranco Nencioni, Nishanth Sastry, Gareth Tyson, Vijay Badrinarayanan, Dmytro Karamshuk, Jigna Chandaria, and Jon Crowcroft. 2016. SCORE: Exploiting Global Broadcasts to Create Offline Personal Channels for On-Demand Access. IEEE/ACM Trans. Netw. 24, 4 (August 2016), 2429-2442. DOI:https://doi.org/10.1109/TNET.2015.2456186",
    },
    "17_win16": {
        "ccs":"Human-centered Computing",
        "title": "Who is to change? nudging and provocative communication discussed through Lögstrup's ontological ethics.",
        "year": 2016,
        "scores": [3, 4, 4],
        "category": "Top-rated",
        "keyword": "Natural Interaction",
        "section": "Thomas Dyrmann Winkel, Thessa Jensen, and Sören Bolvig Poulsen. 2016. Who is to change? nudging and provocative communication discussed through Lögstrup's ontological ethics. SIGCAS Comput. Soc. 45, 3 (January 2016), 337-343. DOI:https://doi.org/10.1145/2874239.2874289",
    },
    "18_mck82": {
        "ccs":"Theory of Computation",
        "title": "Design of software for distributed/multiprocessor systems.",
        "year": 1982,
        "scores": [3, 3, 4],
        "category": "Top-rated",
        "keyword": "Computation",
        "section": "Terrence R. Mckelvey and Dharma P. Agrawal. 1982. Design of software for distributed/multiprocessor systems. In Proceedings of the June 7-10, 1982, national computer conference (AFIPS ‚1982). Association for Computing Machinery, New York, NY, USA, 239-249. DOI:https://doi.org/10.1145/1500774.1500803",
    },
    "19_oga93": {
        "ccs":"Human-centered Computing",
        "title": "Design strategies for scenario-based hypermedia: description of its structure, dynamics, and style.",
        "year": 1993,
        "scores": [3, 3, 4],
        "category": "Top-rated",
        "keyword": "NUI",
        "section": "Ryuichi Ogawa, Eiichiro Tanaka, Daigo Taguchi, and Komei Harada. 1993. Design strategies for scenario-based hypermedia: description of its structure, dynamics, and style. In Proceedings of the ACM conference on Hypertext (ECHT ‚1992). Association for Computing Machinery, New York, NY, USA, 71-80. DOI:https://doi.org/10.1145/168466.168494",
    },
    "20_goc1999": {
        "ccs":"Information Systems",
        "title": "C++ classes for linking optimization with complex simulations.",
        "year": 1999,
        "scores": [3, 3, 4],
        "category": "Top-rated",
        "keyword": "Computation",
        "section": "Mark S. Gockenbach, Matthew J. Petro, and William W. Symes. 1999. C++ classes for linking optimization with complex simulations. ACM Trans. Math. Softw. 25, 2 (June 1999), 191–212. DOI:https://doi.org/10.1145/317275.317280",
    },
    "21_aga00": {
        "ccs":"Information Systems",
        "title": "Depth first generation of long patterns.",
        "year": 2000,
        "scores": [3, 3, 4],
        "category": "Top-rated",
        "keyword": "Computation",
        "section": "Ramesh C. Agarwal, Charu C. Aggarwal, and V. V. V. Prasad. 2000. Depth first generation of long patterns. In Proceedings of the sixth ACM SIGKDD international conference on Knowledge discovery and data mining (KDD ’00). Association for Computing Machinery, New York, NY, USA, 108–118. DOI:https://doi.org/10.1145/347090.347114",
    },
    "22_hin08": {
        "ccs":"Information Systems",
        "title": "Creating human-machine synergy in negotiation support systems: towards the pocket negotiator.",
        "year": 2008,
        "scores": [3, 3, 4],
        "category": "Top-rated",
        "keyword": "NUI",
        "section": "Koen V. Hindriks and Catholijn M. Jonker. 2008. Creating human-machine synergy in negotiation support systems: towards the pocket negotiator. In Proceedings of the 1st International Working Conference on Human Factors and Computational Models in Negotiation (HuCom ‚2008). Association for Computing Machinery, New York, NY, USA, 47-54. DOI:https://doi.org/10.1145/1609170.1609176",
    },
    "23_abr09": {
        "ccs":"Human-centered Computing",
        "title": "Patterns or claims: do they help in communicating design advice?",
        "year": 2009,
        "scores": [3, 3, 4],
        "category": "Top-rated",
        "keyword": "NUI",
        "section": "George Abraham and Michael E. Atwood. 2009. Patterns or claims: do they help in communicating design advice? In Proceedings of the 21st Annual Conference of the Australian Computer-Human Interaction Special Interest Group: Design: Open 24/7 (OZCHI ‚2009). Association for Computing Machinery, New York, NY, USA, 25-32. DOI:https://doi.org/10.1145/1738826.1738831",
    },
    "24_lia10": {
        "ccs":"Information Systems",
        "title": "Partial matching of garment panel shapes with dynamic sketching design.",
        "year": 2010,
        "scores": [3, 3, 4],
        "category": "Top-rated",
        "keyword": "Natural Interaction",
        "section": "Shuang Liang, Rong-Hua Li, George Baciu, Eddie C. L. Chan, and Dejun Zheng. 2010. Partial matching of garment panel shapes with dynamic sketching design. In Proceedings of the 1st Augmented Human International Conference (AH ‚2010). Association for Computing Machinery, New York, NY, USA, Article 16, 1-6. DOI:https://doi.org/10.1145/1785455.1785471",
    },
    "25_mac94": {
        "ccs":"Computing Methodologies",
        "title": "Developing calendar visualizers for the information visualizer.",
        "year": 1994,
        "scores": [3, 3, 3],
        "category": "Origin of clusters",
        "keyword": "",
        "section": "Jock D. Mackinlay, George G. Robertson, and Robert DeLine. 1994. Developing calendar visualizers for the information visualizer. In Proceedings of the 7th annual ACM symposium on User interface software and technology (UIST ‚1994). Association for Computing Machinery, New York, NY, USA, 109-118. DOI:https://doi.org/10.1145/192426.192470",
    },
    "26_omi99": {
        "ccs":"Computing Methodologies",
        "title": "Tuple centres for the coordination of Internet agents.",
        "year": 1999,
        "scores": [3, 3, 3],
        "category": "Origin of clusters",
        "keyword": "",
        "section": "Andrea Omicini and Franco Zambonelli. 1999. Tuple centres for the coordination of Internet agents. In Proceedings of the 1999 ACM symposium on Applied computing (SAC ‚1999). Association for Computing Machinery, New York, NY, USA, 183-190. DOI:https://doi.org/10.1145/298151.298231",
    },
    "27_dac99": {
        "ccs":"Human-centered Computing",
        "title": "Haptic sculpting of dynamic surfaces.",
        "year": 1999,
        "scores": [1, 4, 4],
        "category": "Origin of clusters",
        "keyword": "",
        "section": "Frank Dachille, Hong Qin, Arie Kaufman, and Jihad El-Sana. 1999. Haptic sculpting of dynamic surfaces. In Proceedings of the 1999 symposium on Interactive 3D graphics (I3D ‚1999). Association for Computing Machinery, New York, NY, USA, 103-110. DOI:https://doi.org/10.1145/300523.300535",
    },
    "28_gei09": {
        "ccs":"Networks",
        "title": "Cognitive frequency hopping based on interference prediction: theory and experimental results.",
        "year": 2009,
        "scores": [3, 3, 3],
        "category": "Origin of clusters",
        "keyword": "",
        "section": "Stefan Geirhofer, John Z. Sun, Lang Tong, and Brian M. Sadler. 2009. Cognitive frequency hopping based on interference prediction: theory and experimental results. SIGMOBILE Mob. Comput. Commun. Rev. 13, 2 (September 2009), 49-61. DOI:https://doi.org/10.1145/1621076.1621082",
    },
    "29_du03": {
        "ccs":"Computing Methodologies",
        "title": "Interactive shape design using volumetric implicit PDEs.",
        "year": 2003,
        "scores": [3, 3, 3],
        "category": "Origin of clusters",
        "keyword": "",
        "section": "Haixia Du. 2003. Interactive shape design using volumetric implicit PDEs. In Proceedings of the eighth ACM symposium on Solid modeling and applications (SM ’03). Association for Computing Machinery, New York, NY, USA, 235–246. DOI:https://doi.org/10.1145/781606.781642",
    },
    "30_sha04": {
        "ccs":"Networks",
        "title": "Enhancing both network and user performance for networks supporting best effort traffic.",
        "year": 2004,
        "scores": [3, 3, 3],
        "category": "Origin of clusters",
        "keyword": "",
        "section": "Shanchieh Jay Yang and Gustavo de Veciana. 2004. Enhancing both network and user performance for networks supporting best effort traffic. IEEE/ACM Trans. Netw. 12, 2 (April 2004), 349–360. DOI:https://doi.org/10.1109/TNET.2004.826280",
    },
    "31_gaj05": {
        "ccs":"Computing Methodologies",
        "title": "System design extreme makeover.",
        "year": 2005,
        "scores": [2, 4, 3],
        "category": "Origin of clusters",
        "keyword": "",
        "section": "D. D. Gajski. 2005. System design extreme makeover. In Proceedings of the 2nd ACM/IEEE International Conference on Formal Methods and Models for Co-Design (MEMOCODE ‚2005). IEEE Computer Society, USA, 71-75. DOI:https://doi.org/10.1109/MEMCOD.2005.1487895",
    },
    "32_du05": {
        "ccs":"Computing Methodologies",
        "title": "A shape design system using volumetric implicit PDEs.",
        "year": 2005,
        "scores": [3, 3, 3],
        "category": "Origin of clusters",
        "keyword": "",
        "section": "Haixia Du and Hong Qin. 2005. A shape design system using volumetric implicit PDEs. In ACM SIGGRAPH 2005 Courses (SIGGRAPH ’05). Association for Computing Machinery, New York, NY, USA, 116–es. DOI:https://doi.org/10.1145/1198555.1198647",
    },
    "33_dod08": {
        "ccs":"Applied Computing",
        "title": "Leveraging laptops for low-cost, full-fledged outdoor robotics.",
        "year": 2008,
        "scores": [3, 3, 3],
        "category": "Origin of clusters",
        "keyword": "",
        "section": "Zachary Dodds. 2008. Leveraging laptops for low-cost, full-fledged outdoor robotics. J. Comput. Sci. Coll. 24, 1 (October 2008), 158-166.",
    },
    "34_pas11": {
        "ccs":"Computer Systems Organization",
        "title": "Modelling inter-contact times in social pervasive networks.",
        "year": 2011,
        "scores": [3, 3, 3],
        "category": "Origin of clusters",
        "keyword": "",
        "section": "Andrea Passarella, Marco Conti, Chiara Boldrini, and Robin I.M. Dunbar. 2011. Modelling inter-contact times in social pervasive networks. In Proceedings of the 14th ACM international conference on Modeling, analysis and simulation of wireless and mobile systems (MSWiM ‚2011). Association for Computing Machinery, New York, NY, USA, 333-340. DOI:https://doi.org/10.1145/2068897.2068955",
    },   
    "35_sub13": {
        "ccs":"Software and its Engineering",
        "title": "Artificial connections.",
        "year": 2013,
        "scores": [2, 3, 4],
        "category": "Origin of clusters",
        "keyword": "",
        "section": "Nidhi Subbaraman. 2013. Artificial connections. Commun. ACM 56, 4 (April 2013), 15-17. DOI:https://doi.org/10.1145/2436256.2436261",
    },
    "36_su19": {
        "ccs":"Applied Computing",
        "title": "Toward Generating Realistic Sounds for Soft Bodies: A Review.",
        "year": 2019,
        "scores": [2, 3, 4],
        "category": "Origin of clusters",
        "keyword": "",
        "section": "Feng Su and Chris Joslin. 2019. Toward Generating Realistic Sounds for Soft Bodies: A Review. In Proceedings of the 14th International Audio Mostly Conference: A Journey in Sound (AM‚2019). Association for Computing Machinery, New York, NY, USA, 199-206. DOI:https://doi.org/10.1145/3356590.3356620",
    },
    "37_mac91": {
        "ccs":"Human-centered Computing",
        "title": "Reaching through analogy: a Design Rationale perspective on roles of analogy.",
        "year": 1991,
        "scores": [3, 2, 3],
        "category": "Origin of clusters",
        "keyword": "",
        "section": "Allan MacLean, Victoria Bellotti, Richard Young, and Thomas Moran. 1991. Reaching through analogy: a Design Rationale perspective on roles of analogy. In Proceedings of the SIGCHI Conference on Human Factors in Computing Systems (CHI ‚1991). Association for Computing Machinery, New York, NY, USA, 167-172. DOI:https://doi.org/10.1145/108844.108869",
    },
    "38_pis03": {
        "ccs":"Information Systems",
        "title": "Submit! a web-based system for automatic program critiquing.",
        "year": 2003,
        "scores": [3, 2, 3],
        "category": "Origin of clusters",
        "keyword": "",
        "section": "Yusuf Pisan, Debbie Richards, Anthony Sloane, Helena Koncek, and Simon Mitchell. 2003. Submit! a web-based system for automatic program critiquing. In Proceedings of the fifth Australasian conference on Computing education - Volume 20 (ACE ‚2003). Australian Computer Society, Inc., AUS, 59-68.",
    },
    "39_sch05": {
        "ccs":"Software and its Engineering",
        "title": "Middleware for protocol-based coordination in dynamic networks.",
        "year": 2005,
        "scores": [2, 4, 2],
        "category": "Origin of clusters",
        "keyword": "",
        "section": "Kurt Schelfthout, Danny Weyns, and Tom Holvoet. 2005. Middleware for protocol-based coordination in dynamic networks. In Proceedings of the 3rd international workshop on Middleware for pervasive and ad-hoc computing (MPAC ’05). Association for Computing Machinery, New York, NY, USA, 1–8. DOI:https://doi.org/10.1145/1101480.1101488",
    },
    "40_mar06": {
        "ccs":"Computing Methodologies",
        "title": "System-level process-driven variability analysis for single and multiple voltage-frequency island systems.",
        "year": 2006,
        "scores": [3, 2, 3],
        "category": "Origin of clusters",
        "keyword": "",
        "section": "Diana Marculescu and Siddharth Garg. 2006. System-level process-driven variability analysis for single and multiple voltage-frequency island systems. In Proceedings of the 2006 IEEE/ACM international conference on Computer-aided design (ICCAD ‚2006). Association for Computing Machinery, New York, NY, USA, 541-546. DOI:https://doi.org/10.1145/1233501.1233611",
    },
    "41_yu07": {
        "ccs":"Hardware",
        "title": "Aggressive snoop reduction for synchronized producer-consumer communication in energy-efficient embedded multi-processors.",
        "year": 2007,
        "scores": [3, 1, 4],
        "category": "Origin of clusters",
        "keyword": "",
        "section": "Chenjie Yu and Peter Peter Petrov. 2007. Aggressive snoop reduction for synchronized producer-consumer communication in energy-efficient embedded multi-processors. In Proceedings of the 5th IEEE/ACM international conference on Hardware/software codesign and system synthesis (CODES+ISSS ‚2007). Association for Computing Machinery, New York, NY, USA, 245-250. DOI:https://doi.org/10.1145/1289816.1289876",
    },
    "42_sim12": {
        "ccs":"Human-centered Computing",
        "title": "Merging tangible buttons and spatial augmented reality to support ubiquitous prototype designs.",
        "year": 2012,
        "scores": [2, 3, 3],
        "category": "Origin of clusters",
        "keyword": "",
        "section": "Tim M. Simon, Ross T. Smith, Bruce Thomas, Stewart Von Itzstein, Mark Smith, Joonsuk Park, and Jun Park. 2012. Merging tangible buttons and spatial augmented reality to support ubiquitous prototype designs. In Proceedings of the Thirteenth Australasian User Interface Conference - Volume 126 (AUIC ‚2012). Australian Computer Society, Inc., AUS, 29-38.",
    },
    "43_xu17": {
        "ccs":"Information Systems",
        "title": "Online Deduplication for Databases.",
        "year": 2017,
        "scores": [3, 3, 2],
        "category": "Origin of clusters",
        "keyword": "",
        "section": "Xu, L., Pavlo, A., Sengupta, S., & Ganger, G. R. (2017). Online Deduplication for Databases. Proceedings of the 2017 ACM International Conference on Management of Data, 1355–1368. https://doi.org/10.1145/3035918.3035938",
    },
    "44_rus18": {
        "ccs":"Human-centered Computing",
        "title": "Designing Coherent Gesture Sets for Multi-scale Navigation on Tabletops.",
        "year": 2018,
        "scores": [1, 4, 3],
        "category": "Origin of clusters",
        "keyword": "",
        "section": "Vít Rusnúk, Caroline Appert, Olivier Chapuis, and Emmanuel Pietriga. 2018. Designing Coherent Gesture Sets for Multi-scale Navigation on Tabletops. In Proceedings of the 2018 CHI Conference on Human Factors in Computing Systems (CHI ‚2018). Association for Computing Machinery, New York, NY, USA, Paper 142, 1-12. DOI:https://doi.org/10.1145/3173574.3173716",
    },
    "45_ham81": {
        "ccs":"Theory of Computation",
        "title": "Database description with SDM: a semantic database model.",
        "year": 1981,
        "scores": [2, 3, 2],
        "category": "Origin of clusters",
        "keyword": "",
        "section": "Hammer, M., & Mc Leod, D. (1981). Database description with SDM: a semantic database model. ACM Trans. Database Syst., 6(3), 351–386. https://doi.org/10.1145/319587.319588",
    },
    "46_car90": {
        "ccs":"Software and its Engineering",
        "title": "The point of view notion for multiple inheritance.",
        "year": 1990,
        "scores": [2, 3, 2],
        "category": "Origin of clusters",
        "keyword": "",
        "section": "Bernard Carré and Jean-Marc Geib. 1990. The point of view notion for multiple inheritance. In Proceedings of the European conference on object-oriented programming on Object-oriented programming systems, languages, and applications (OOPSLA/ECOOP ‚1990). Association for Computing Machinery, New York, NY, USA, 312-321. DOI:https://doi.org/10.1145/97945.97983",
    },
    "47_oto94": {
        "ccs":"Software and its Engineering",
        "title": "An opportunistic installation service: economy of scale for asynchronous reads.",
        "year": 1994,
        "scores": [2, 3, 2],
        "category": "Origin of clusters",
        "keyword": "",
        "section": "James O'Toole and Liuba Shrira. 1994. An opportunistic installation service: economy of scale for asynchronous reads. In Proceedings of the 6th workshop on ACM SIGOPS European workshop: Matching operating systems to application needs (EW 6). Association for Computing Machinery, New York, NY, USA, 147-150. DOI:https://doi.org/10.1145/504390.504430",
    },
    "48_man97": {
        "ccs":"Computing Methodologies",
        "title": "Panel on transportation and logistics modeling.",
        "year": 1997,
        "scores": [2, 3, 2],
        "category": "Origin of clusters",
        "keyword": "",
        "section": "Mani S. Manivannan, Eric Miller, Mark Brazier, H. Donald Ratliff, and John S. Carson. 1997. Panel on transportation and logistics modeling. In Proceedings of the 29th conference on Winter simulation (WSC ‚1997). IEEE Computer Society, USA, 1244-1250. DOI:https://doi.org/10.1145/268437.268767",
    },
    "49_ste99": {
        "ccs":"Software and its Engineering",
        "title": "A design analysis of a hybrid technology multithreaded architecture for petaflops scale computation3.",
        "year": 1999,
        "scores": [3, 2, 2],
        "category": "Origin of clusters",
        "keyword": "",
        "section": "Thomas Sterling and Larry Bergman. 1999. A design analysis of a hybrid technology multithreaded architecture for petaflops scale computation3. In Proceedings of the 13th international conference on Supercomputing (ICS ‚1999). Association for Computing Machinery, New York, NY, USA, 286-293. DOI:https://doi.org/10.1145/305138.305205",
    },
    "50_Gaf99": {
        "ccs":"Software and its Engineering",
        "title": "Robots: a real-time systems architectural style.",
        "year": 1999,
        "scores": [1, 3, 3],
        "category": "Origin of clusters",
        "keyword": "",
        "section": "Vered Gafni. 1999. Robots: a real-time systems architectural style. In Proceedings of the 7th European software engineering conference held jointly with the 7th ACM SIGSOFT international symposium on Foundations of software engineering (ESEC/FSE-7). Springer-Verlag, Berlin, Heidelberg, 57-74.",
    },
    "51_gan01": {
        "ccs":"Computing Methodologies",
        "title": "Managing event traces for a web front-end to a parallel simulation.",
        "year": 2001,
        "scores": [3, 2, 2],
        "category": "Origin of clusters",
        "keyword": "",
        "section": "Boon Ping Gan, Li Liu, Zhengrong Ji, Stephen J. Turner, and Wentong Cai. 2001. Managing event traces for a web front-end to a parallel simulation. In Proceedings of the 33nd conference on Winter simulation (WSC ‚2001). IEEE Computer Society, USA, 637-644.",
    },
    "52_thi01": {
        "ccs":"Hardware",
        "title": "Usability analysis with Markov models.",
        "year": 2001,
        "scores": [3, 2, 2],
        "category": "Origin of clusters",
        "keyword": "",
        "section": "Thimbleby, H., Cairns, P., & Jones, M. (2001). Usability analysis with Markov models. ACM Trans. Comput.-Hum. Interact., 8(2), 99–132. https://doi.org/10.1145/376929.376941",
    },
    "53_als14": {
        "ccs":"Information Systems",
        "title": "Storage management in AsterixDB.",
        "year": 2014,
        "scores": [3, 2, 2],
        "category": "Origin of clusters",
        "keyword": "",
        "section": "Alsubaiee, S., Behm, A., Borkar, V., Heilbron, Z., Kim, Y.-S., Carey, M. J., Dreseler, M., & Li, C. (2014). Storage management in AsterixDB. Proceedings of the VLDB Endowment International Conference on Very Large Data Bases, 7(10), 841–852. https://doi.org/10.14778/2732951.2732958",
    },
    "54_wan16": {
        "ccs":"Software and its Engineering",
        "title": "Dynamic Memory Balancing for Virtualization.",
        "year": 2016,
        "scores": [2, 1, 4],
        "category": "Origin of clusters",
        "keyword": "",
        "section": "Wang, Z., Wang, X., Hou, F., Luo, Y., & Wang, Z. (2016). Dynamic Memory Balancing for Virtualization. ACM Trans. Archit. Code Optim., 13(1), 1–25. https://doi.org/10.1145/2851501",
    },
    "55_zha18": {
        "ccs":"Hardware",
        "title": "Composable Building Blocks to Open up Processor Design.",
        "year": 2018,
        "scores": [3, 1, 3],
        "category": "Origin of clusters",
        "keyword": "",
        "section": "Zhang, S., A. Wright, T. Bourgeat, and A. Arvind. 2018. “Composable Building Blocks to Open up Processor Design.” In 2018 51st Annual IEEE/ACM International Symposium on Microarchitecture (MICRO), 68–81. ieeexplore.ieee.org.",
    },
    "56_ram86": {
        "ccs":"Hardware",
        "title": "On driving many long wires in a VLSI layout.",
        "year": 1986,
        "scores": [3, 1, 2],
        "category": "Origin of clusters",
        "keyword": "",
        "section": "Vijaya Ramachandran. 1986. On driving many long wires in a VLSI layout. J. ACM 33, 4 (August 1986), 687-701. DOI:https://doi.org/10.1145/6490.6784",
    },
    "57_rot94": {
        "ccs":"Computing Methodologies",
        "title": "Interactive graphic design using automatic presentation knowledge.",
        "year": 1994,
        "scores": [2, 2, 2],
        "category": "Origin of clusters",
        "keyword": "",
        "section": "Steven F. Roth, John Kolojejchick, Joe Mattis, and Jade Goldstein. 1994. Interactive graphic design using automatic presentation knowledge. In Proceedings of the SIGCHI Conference on Human Factors in Computing Systems (CHI ‚1994). Association for Computing Machinery, New York, NY, USA, 112-117. DOI:https://doi.org/10.1145/191666.191719",
    },
    "58_paa95": {
        "ccs":"Software and its Engineering",
        "title": "Attribute grammar paradigms—a high-level methodology in language implementation.",
        "year": 1995,
        "scores": [3, 2, 1],
        "category": "Origin of clusters",
        "keyword": "",
        "section": "Paakki, J. (1995). Attribute grammar paradigms—a high-level methodology in language implementation. ACM Comput. Surv., 27(2), 196–255. https://doi.org/10.1145/210376.197409",
    },
    "59_yu97": {
        "ccs":"Hardware",
        "title": " Preserving HDL synthesis hierarchy for cell placement.",
        "year": 1997,
        "scores": [2, 2, 2],
        "category": "Origin of clusters",
        "keyword": "",
        "section": "Yu-Wen Tsay, Wen-Jong Fang, Allen C.-H. Wu, and Youn-Long Lin. 1997. Preserving HDL synthesis hierarchy for cell placement. In Proceedings of the 1997 international symposium on Physical design (ISPD ‚1997). Association for Computing Machinery, New York, NY, USA, 169-174. DOI:https://doi.org/10.1145/267665.267709",
    },
    "60_art02": {
        "ccs":"Computer Systems Organization",
        "title": "Global scheduler properties derived from local restrictions.",
        "year": 2002,
        "scores": [3, 1, 2],
        "category": "Origin of clusters",
        "keyword": "",
        "section": "Thomas Arts and Juan José Sánchez Penas. 2002. Global scheduler properties derived from local restrictions. In Proceedings of the 2002 ACM SIGPLAN workshop on Erlang (ERLANG ’02). Association for Computing Machinery, New York, NY, USA, 49–57. DOI:https://doi.org/10.1145/592849.592856",
    },
    "61_bla03": {
        "ccs":"Theory of Computation",
        "title": "Budget balanced mechanisms for the multicast pricing problem with rates.",
        "year": 2003,
        "scores": [3, 1, 2],
        "category": "Origin of clusters",
        "keyword": "",
        "section": "Markus Bläser and Bodo Manthey. 2003. Budget balanced mechanisms for the multicast pricing problem with rates. In Proceedings of the 4th ACM conference on Electronic commerce (EC ‚2003). Association for Computing Machinery, New York, NY, USA, 194-195. DOI:https://doi.org/10.1145/779928.779955",
    },
    "62_che07": {
        "ccs":"Computing Methodologies",
        "title": "Shape sensitivity of constructive representations.",
        "year": 2007,
        "scores": [1, 2, 3],
        "category": "Origin of clusters",
        "keyword": "",
        "section": "Jiaqin Chen, Michael Freytag, and Vadim Shapiro. 2007. Shape sensitivity of constructive representations. In Proceedings of the 2007 ACM symposium on Solid and physical modeling (SPM ‚2007). Association for Computing Machinery, New York, NY, USA, 85-95. DOI:https://doi.org/10.1145/1236246.1236260",
    },
    "63_nat08": {
        "ccs":"Information Systems",
        "title": "CollaboraTV: making television viewing social again.",
        "year": 2008,
        "scores": [2, 2, 2],
        "category": "Origin of clusters",
        "keyword": "",
        "section": "Mukesh Nathan, Chris Harrison, Svetlana Yarosh, Loren Terveen, Larry Stead, and Brian Amento. 2008. CollaboraTV: making television viewing social again. In Proceedings of the 1st international conference on Designing interactive user experiences for TV and video (UXTV ’08). Association for Computing Machinery, New York, NY, USA, 85–94. DOI:https://doi.org/10.1145/1453805.1453824",
    },
    "64_koo09": {
        "ccs":"Information Systems",
        "title": "A tale of two synchronizing clocks.",
        "year": 2009,
        "scores": [2, 2, 2],
        "category": "Origin of clusters",
        "keyword": "",
        "section": "Koo, J., Panta, R. K., Bagchi, S., & Montestruque, L. (2009). A tale of two synchronizing clocks. Proceedings of the 7th ACM Conference on Embedded Networked Sensor Systems, 239–252. https://doi.org/10.1145/1644038.1644062",
    },
    "65_cip10": {
        "ccs":"Software and its Engineering",
        "title": "Reverse inheritance in statically typed object-oriented programming languages.",
        "year": 2010,
        "scores": [2, 2, 2],
        "category": "Origin of clusters",
        "keyword": "",
        "section": "Ciprian-Bogdan Chirilä, Markku Sakkinen, Philippe Lahire, and Ioan Jurca. 2010. Reverse inheritance in statically typed object-oriented programming languages. In Proceedings of the 4th Workshop on MechAnisms for SPEcialization, Generalization and inHerItance (MASPEGHI ‚2010). Association for Computing Machinery, New York, NY, USA, Article 5, 1‚Äì5. DOI:https://doi.org/10.1145/1929999.1930004",
    },
    "66_hun11": {
        "ccs":"Social and Professional Topics",
        "title": "California speedway: a concurrent programming project for beginners.",
        "year": 2011,
        "scores": [3, 1, 2],
        "category": "Origin of clusters",
        "keyword": "",
        "section": "John M. Hunt and Tim Willison. 2011. California speedway: a concurrent programming project for beginners. In Proceedings of the 49th Annual Southeast Regional Conference (ACM-SE ‚2011). Association for Computing Machinery, New York, NY, USA, 7-12. DOI:https://doi.org/10.1145/2016039.2016052",
    },
    "67_zoh15": {
        "ccs":"Applied Computing",
        "title": "Bitcoin: under the hood.",
        "year": 2015,
        "scores": [3, 1, 2],
        "category": "Origin of clusters",
        "keyword": "",
        "section": "Aviv Zohar. 2015. Bitcoin: under the hood. Commun. ACM 58, 9 (August 2015), 104–113. DOI:https://doi.org/10.1145/2701411",
    },
    "68_had16": {
        "ccs":"Software and its Engineering",
        "title": "Toward disposable domain-specific aspect languages.",
        "year": 2016,
        "scores": [3, 1, 2],
        "category": "Origin of clusters",
        "keyword": "",
        "section": "Arik Hadas and David H. Lorenz. 2016. Toward disposable domain-specific aspect languages. In Companion Proceedings of the 15th International Conference on Modularity (MODULARITY Companion 2016). Association for Computing Machinery, New York, NY, USA, 83-85. DOI:https://doi.org/10.1145/2892664.2892676",
    },
    "69_nak18": {
        "ccs":"Networks",
        "title": "Practical Service Chaining based on IP Routing.",
        "year": 2018,
        "scores": [3, 1, 2],
        "category": "Origin of clusters",
        "keyword": "",
        "section": "Ryo Nakamura, Yukito Ueno, Teppei Kamata, Kazuki Shimizu, Takashi Tomine, and Takayuki Watanabe. 2018. Practical Service Chaining based on IP Routing. In Proceedings of the Asian Internet Engineering Conference (AINTEC ‚2018). Association for Computing Machinery, New York, NY, USA, 24-31. DOI:https://doi.org/10.1145/3289166.3289170",
    },
    "70_fer92": {
        "ccs":"Applied Computing",
        "title": "HyperWeb: a framework for hypermedia-based environments.",
        "year": 1992,
        "scores": [1, 2, 2],
        "category": "Origin of clusters",
        "keyword": "",
        "section": "James C. Ferrans, David W. Hurst, Michael A. Sennett, Burton M. Covnot, Wenguang Ji, Peter Kajka, and Wei Ouyang. 1992. HyperWeb: a framework for hypermedia-based environments. In Proceedings of the fifth ACM SIGSOFT symposium on Software development environments (SDE 5). Association for Computing Machinery, New York, NY, USA, 1-10. DOI:https://doi.org/10.1145/142868.142899",
    },
    "71_mur96": {
        "ccs":"Software and its Engineering",
        "title": "Issues and answers in CAD tool interoperability.",
        "year": 1996,
        "scores": [2, 2, 1],
        "category": "Origin of clusters",
        "keyword": "",
        "section": "Mike Murray, Uwe B. Meding, Bill Berg, Yatin Trivedi, Bill McCaffrey, and Ted Vucurevich. 1996. Issues and answers in CAD tool interoperability. In Proceedings of the 33rd annual Design Automation Conference (DAC ’96). Association for Computing Machinery, New York, NY, USA, 509–514. DOI:https://doi.org/10.1145/240518.240615",
    },
    "72_car01": {
        "ccs":"Information Systems",
        "title": "Design and evaluation of a wide-area event notification service.",
        "year": 2001,
        "scores": [2, 2, 1],
        "category": "Origin of clusters",
        "keyword": "",
        "section": "Carzaniga, A., Rosenblum, D. S., & Wolf, A. L. (2001). Design and evaluation of a wide-area event notification service. ACM Transactions on Computer Systems, 19(3), 332–383. https://doi.org/10.1145/380749.380767",
    },
    "73_agg03": {
        "ccs":"Information Systems",
        "title": "A framework for clustering evolving data streams.",
        "year": 2003,
        "scores": [3, 1, 1],
        "category": "Origin of clusters",
        "keyword": "",
        "section": "Charu C. Aggarwal, Jiawei Han, Jianyong Wang, and Philip S. Yu. 2003. A framework for clustering evolving data streams. In Proceedings of the 29th international conference on Very large data bases - Volume 29 (VLDB ’03). VLDB Endowment, 81–92.",
    },
    "74_str04": {
        "ccs":"Software and its Engineering",
        "title": "Refactoring Class Hierarchies with KABA.",
        "year": 2004,
        "scores": [2, 2, 1],
        "category": "Origin of clusters",
        "keyword": "",
        "section": "Streckenbach, Mirko, and Gregor Snelting. 2004. “Refactoring Class Hierarchies with KABA.” In Proceedings of the 19th Annual ACM SIGPLAN Conference on Object-Oriented Programming, Systems, Languages, and Applications, 315–30. OOPSLA ’04. New York, NY, USA: Association for Computing Machinery.",
    },
    "75_wil05": {
        "ccs":"Software and its Engineering",
        "title": "Arithmetic with measurements on dynamically-typed object-oriented languages.",
        "year": 2005,
        "scores": [2, 1, 2],
        "category": "Origin of clusters",
        "keyword": "",
        "section": "Hernán Wilkinson, Máximo Prieto, and Luciano Romeo. 2005. Arithmetic with measurements on dynamically-typed object-oriented languages. In Companion to the 20th annual ACM SIGPLAN conference on Object-oriented programming, systems, languages, and applications (OOPSLA ‚Äô05). Association for Computing Machinery, New York, NY, USA, 292‚Äì300. DOI:https://doi.org/10.1145/1094855.1094964",
    },
    "76_bic06": {
        "ccs":"Computing Methodologies",
        "title": "Software frameworks for advanced procurement auction markets.",
        "year": 2006,
        "scores": [1, 2, 2],
        "category": "Origin of clusters",
        "keyword": "",
        "section": "Martin Bichler and Jayant R. Kalagnanam. 2006. Software frameworks for advanced procurement auction markets. Commun. ACM 49, 12 (December 2006), 104-108. DOI:https://doi.org/10.1145/1183236.1183239",
    },
    "77_jia09": {
        "ccs":"General and Reference",
        "title": "Cooperative Content Distribution and Traffic Engineering in an ISP Network.",
        "year": 2009,
        "scores": [1, 1, 3],
        "category": "Origin of clusters",
        "keyword": "",
        "section": "Jiang, Wenjie, Rui Zhang-Shen, Jennifer Rexford, and Mung Chiang. 2009. “Cooperative Content Distribution and Traffic Engineering in an ISP Network.” In Proceedings of the Eleventh International Joint Conference on Measurement and Modeling of Computer Systems, 239–50. SIGMETRICS ’09. New York, NY, USA: Association for Computing Machinery.",
    },
    "78_ram09": {
        "ccs":"Applied Computing",
        "title": "An Object-Oriented Design for Two-Dimensional Vortex Particle Methods.",
        "year": 2009,
        "scores": [3, 1, 1],
        "category": "Origin of clusters",
        "keyword": "",
        "section": "Prabhu Ramachandran and M. Ramakrishna. 2009. An Object-Oriented Design for Two-Dimensional Vortex Particle Methods. ACM Trans. Math. Softw. 36, 4, Article 18 (August 2009), 28 pages. DOI:https://doi.org/10.1145/1555386.1555387",
    },
    "79_lin10": {
        "ccs":"Software and its Engineering",
        "title": "Does size matter? a preliminary investigation of the consequences of powerlaws in software.",
        "year": 2010,
        "scores": [1, 1, 3],
        "category": "Origin of clusters",
        "keyword": "",
        "section": "Joshua Lindsay, James Noble, and Ewan Tempero. 2010. Does size matter? a preliminary investigation of the consequences of powerlaws in software. In Proceedings of the 2010 ICSE Workshop on Emerging Trends in Software Metrics (WETSoM ‚2010). Association for Computing Machinery, New York, NY, USA, 16-23. DOI:https://doi.org/10.1145/1809223.1809226",
    },
    "80_sim12": {
        "ccs":"Computing Methodologies",
        "title": "Magnetic substrate for use with tangible spatial augmented reality in rapid prototyping workflows.",
        "year": 2012,
        "scores": [2, 1, 2],
        "category": "Origin of clusters",
        "keyword": "",
        "section": "Tim M. Simon and Ross T. Smith. 2012. Magnetic substrate for use with tangible spatial augmented reality in rapid prototyping workflows. In Proceedings of the Thirteenth Australasian User Interface Conference - Volume 126 (AUIC ‚2012). Australian Computer Society, Inc., AUS, 95-96.",
    },
    "81_mar12": {
        "ccs":"Hardware",
        "title": "Why on-chip cache coherence is here to stay.",
        "year": 2012,
        "scores": [1, 2, 2],
        "category": "Origin of clusters",
        "keyword": "",
        "section": "Milo M. K. Martin, Mark D. Hill, and Daniel J. Sorin. 2012. Why on-chip cache coherence is here to stay. Commun. ACM 55, 7 (July 2012), 78–89. DOI:https://doi.org/10.1145/2209249.2209269",
    },
    "82_wu13": {
        "ccs":"Applied Computing",
        "title": "A survey on XML streaming evaluation techniques.",
        "year": 2013,
        "scores": [1, 2, 2],
        "category": "Origin of clusters",
        "keyword": "",
        "section": "Wu, X., & Theodoratos, D. (2013). A survey on XML streaming evaluation techniques. The VLDB Journal: Very Large Data Bases: A Publication of the VLDB Endowment, 22(2), 177–202. https://doi.org/10.1007/s00778-012-0281-y",
    },
    "83_han13": {
        "ccs":"Information Systems",
        "title": "Using maximum coverage to optimize recommendation systems in e-commerce.",
        "year": 2013,
        "scores": [1, 3, 1],
        "category": "Origin of clusters",
        "keyword": "",
        "section": "Mikael Hammar, Robin Karlsson, and Bengt J. Nilsson. 2013. Using maximum coverage to optimize recommendation systems in e-commerce. In Proceedings of the 7th ACM conference on Recommender systems (RecSys ‚2013). Association for Computing Machinery, New York, NY, USA, 265-272. DOI:https://doi.org/10.1145/2507157.2507169",
    },
    "84_xue17": {
        "ccs":"Networks",
        "title": "A mechanism for mitigating DoS attack in ICN-based internet of things.",
        "year": 2017,
        "scores": [1, 2, 2],
        "category": "Origin of clusters",
        "keyword": "",
        "section": "Haoyue Xue, Yuhong Li, Rahim Rahmani, Theo Kanter, and Xirong Que. 2017. A mechanism for mitigating DoS attack in ICN-based internet of things. In Proceedings of the 1st International Conference on Internet of Things and Machine Learning (IML ‚2017). Association for Computing Machinery, New York, NY, USA, Article 26, 1-10. DOI:https://doi.org/10.1145/3109761.3109787",
    },
    "85_dev17": {
        "ccs":"Theory of Computation",
        "title": "Parametricity versus the universal type.",
        "year": 2017,
        "scores": [1, 2, 2],
        "category": "Origin of clusters",
        "keyword": "",
        "section": "Devriese, D., Patrignani, M., & Piessens, F. (2017). Parametricity versus the universal type. Proc. ACM Program. Lang., 2(POPL), 1–23. https://doi.org/10.1145/3158126",
    },
    "86_saa79": {
        "ccs":"Software and its Engineering",
        "title": " A software high performance APL interpreter.",
        "year": 1979,
        "scores": [1, 1, 2],
        "category": "Origin of clusters",
        "keyword": "",
        "section": "Harry J. Saal and Zvi Weiss. 1979. A software high performance APL interpreter. In Proceedings of the international conference on APL: part 1 (APL ‚1979). Association for Computing Machinery, New York, NY, USA, 74-81. DOI:https://doi.org/10.1145/800136.804441",
    },
    "87_agg86": {
        "ccs":"Computer Systems Organization",
        "title": "Geometric applications of a matrix searching algorithm.",
        "year": 1986,
        "scores": [1, 2, 1],
        "category": "Origin of clusters",
        "keyword": "",
        "section": "A Aggarwal, M Klawe, S Moran, P Shor, and R Wilber. 1986. Geometric applications of a matrix searching algorithm. In Proceedings of the second annual symposium on Computational geometry (SCG ‚1986). Association for Computing Machinery, New York, NY, USA, 285-292. DOI:https://doi.org/10.1145/10515.10546",
    },
    "88_ols92": {
        "ccs":"Information Systems",
        "title": "How a group-editor changes the character of a design meeting as well as its outcome.",
        "year": 1992,
        "scores": [1, 1, 2],
        "category": "Origin of clusters",
        "keyword": "",
        "section": "Judith S. Olson, Gary M. Olson, Marianne Storrösten, and Mark Carter. 1992. How a group-editor changes the character of a design meeting as well as its outcome. In Proceedings of the 1992 ACM conference on Computer-supported cooperative work (CSCW ‚1992). Association for Computing Machinery, New York, NY, USA, 91-98. DOI:https://doi.org/10.1145/143457.143466",
    },
    "89_ols93": {
        "ccs":"Human-centered Computing",
        "title": "Groupwork close up: a comparison of the group design process with and without a simple group editor. ",
        "year": 1993,
        "scores": [1, 2, 1],
        "category": "Origin of clusters",
        "keyword": "",
        "section": "Olson, J. S., Olson, G. M., Storrøsten, M., & Carter, M. (1993). Groupwork close up: a comparison of the group design process with and without a simple group editor. ACM Transactions on Information and System Security, 11(4), 321–348. https://doi.org/10.1145/159764.159763",
    },
    "90_nan95": {
        "ccs":"Social and Professional Topics",
        "title": "Hypertext design environments and the hypertext design process.",
        "year": 1995,
        "scores": [1, 1, 2],
        "category": "Origin of clusters",
        "keyword": "",
        "section": "Jocelyne Nanard and Marc Nanard. 1995. Hypertext design environments and the hypertext design process. Commun. ACM 38, 8 (August 1995), 49-56. DOI:https://doi.org/10.1145/208344.208347",
    },
    "91_mar96": {
        "ccs":"Software and its Engineering",
        "title": "NILE: wide-area computing for high energy physics.",
        "year": 1996,
        "scores": [1, 1, 2],
        "category": "Origin of clusters",
        "keyword": "",
        "section": "Keith Marzullo, Michael Ogg, Aleta Ricciardi, Alessandro Amoroso, F. Andrew Calkins, and Eric Rothfus. 1996. NILE: wide-area computing for high energy physics. In Proceedings of the 7th workshop on ACM SIGOPS European workshop: Systems support for worldwide applications (EW 7). Association for Computing Machinery, New York, NY, USA, 49-54. DOI:https://doi.org/10.1145/504450.504460",
    },
    "92_adn01": {
        "ccs":"Human-centered Computing",
        "title": "A multiple layered functional data model to support multiple representations and interoperability of GIS: application to urban management systems.",
        "year": 2001,
        "scores": [1, 2, 1],
        "category": "Origin of clusters",
        "keyword": "",
        "section": "Mohamed El Adnani, Kokou Yétongnon, and Djamal Benslimane. 2001. A multiple layered functional data model to support multiple representations and interoperability of GIS: application to urban management systems. In Proceedings of the 9th ACM international symposium on Advances in geographic Information Systems (GIS ‚2001). Association for Computing Machinery, New York, NY, USA, 7-75. DOI:https://doi.org/10.1145/512161.512177",
    },
    "93_sta01": {
        "ccs":"Software and its Engineering",
        "title": "Efficient longest executable path search for programs with complex flows and pipeline effects.",
        "year": 2001,
        "scores": [1, 2, 1],
        "category": "Origin of clusters",
        "keyword": "",
        "section": "Friedhelm Stappert, Andreas Ermedahl, and Jakob Engblom. 2001. Efficient longest executable path search for programs with complex flows and pipeline effects. In Proceedings of the 2001 international conference on Compilers, architecture, and synthesis for embedded systems (CASES ‚2001). Association for Computing Machinery, New York, NY, USA, 132-140. DOI:https://doi.org/10.1145/502217.502240",
    },
    "94_mei01": {
        "ccs":"Computing Methodologies",
        "title": "Learning with mixtures of trees.",
        "year": 2001,
        "scores": [1, 2, 1],
        "category": "Origin of clusters",
        "keyword": "",
        "section": "Meila, M., & Jordan, M. I. (2001). Learning with mixtures of trees. Journal of Machine Learning Research: JMLR, 1, 1–48. https://doi.org/10.1162/153244301753344605",
    },
    "95_agg01": {
        "ccs":"Information Systems",
        "title": "Towards long pattern generation in dense databases.",
        "year": 2011,
        "scores": [1, 1, 2],
        "category": "Origin of clusters",
        "keyword": "",
        "section": "Charu C. Aggarwal. 2001. Towards long pattern generation in dense databases. SIGKDD Explor. Newsl. 3, 1 (July 2001), 20-26. DOI:https://doi.org/10.1145/507533.507537",
    },
    "96_hin08": {
        "ccs":"Software and its Engineering",
        "title": "Software engineering and formal methods.",
        "year": 2008,
        "scores": [1, 1, 2],
        "category": "Origin of clusters",
        "keyword": "",
        "section": "Mike Hinchey, Michael Jackson, Patrick Cousot, Byron Cook, Jonathan P. Bowen, and Tiziana Margaria. 2008. Software engineering and formal methods. Commun. ACM 51, 9 (September 2008), 54–59. DOI:https://doi-org.emedien.ub.uni-muenchen.de/10.1145/1378727.1378742",
    },
    "97_tho09": {
        "ccs":"Information Systems",
        "title": "Learning by seeing: photo viewing in the workplace.",
        "year": 2009,
        "scores": [1, 2, 1],
        "category": "Origin of clusters",
        "keyword": "",
        "section": "Jennifer Thom-Santelli and David R. Millen. 2009. Learning by seeing: photo viewing in the workplace. In Proceedings of the SIGCHI Conference on Human Factors in Computing Systems (CHI ’09). Association for Computing Machinery, New York, NY, USA, 2081–2090. DOI:https://doi.org/10.1145/1518701.1519017",
    },
    "98_fal11": {
        "ccs":"Applied Computing",
        "title": "Optimal cost sharing protocols for scheduling games.",
        "year": 2011,
        "scores": [1, 2, 1],
        "category": "Origin of clusters",
        "keyword": "",
        "section": "Philipp von Falkenhausen and Tobias Harks. 2011. Optimal cost sharing protocols for scheduling games. In Proceedings of the 12th ACM conference on Electronic commerce (EC ‚2011). Association for Computing Machinery, New York, NY, USA, 285-294. DOI:https://doi.org/10.1145/1993574.1993618",
    },
    "99_coo13": {
        "ccs":"Networks",
        "title": "On the risk of misbehaving RPKI authorities.",
        "year": 2013,
        "scores": [1, 1, 2],
        "category": "Origin of clusters",
        "keyword": "",
        "section": "Danny Cooper, Ethan Heilman, Kyle Brogle, Leonid Reyzin, and Sharon Goldberg. 2013. On the risk of misbehaving RPKI authorities. In Proceedings of the Twelfth ACM Workshop on Hot Topics in Networks (HotNets-XII). Association for Computing Machinery, New York, NY, USA, Article 16, 1-7. DOI:https://doi.org/10.1145/2535771.2535787",
    },
    "100_ma15": {
        "ccs":"Software and its Engineering",
        "title": "Can't See the Forest for the Trees: State Restoration's Limitations in Post-silicon Trace Signal Selection.",
        "year": 2015,
        "scores": [1, 2, 1],
        "category": "Origin of clusters",
        "keyword": "",
        "section": "Sai Ma, Debjit Pal, Rui Jiang, Sandip Ray, and Shobha Vasudevan. 2015. Can't See the Forest for the Trees: State Restoration's Limitations in Post-silicon Trace Signal Selection. In Proceedings of the IEEE/ACM International Conference on Computer-Aided Design (ICCAD ‚2015). IEEE Press, 1-8.",
    },
    "101_bha16": {
        "ccs":"Theory of Computation",
        "title": "Hardness Results for Signaling in Bayesian Zero-Sum and Network Routing Games.",
        "year": 2016,
        "scores": [1, 1, 2],
        "category": "Origin of clusters",
        "keyword": "",
        "section": "Umang Bhaskar, Yu Cheng, Young Kun Ko, and Chaitanya Swamy. 2016. Hardness Results for Signaling in Bayesian Zero-Sum and Network Routing Games. In Proceedings of the 2016 ACM Conference on Economics and Computation (EC ‚2016). Association for Computing Machinery, New York, NY, USA, 479-496. DOI:https://doi.org/10.1145/2940716.2940753",
    },
    "102_tem16": {
        "ccs":"Hardware",
        "title": "An Algorithmic Method for the Implantation of Detection-Resistant Covert Hardware Trojans. ",
        "year": 2016,
        "scores": [1, 1, 2],
        "category": "Origin of clusters",
        "keyword": "",
        "section": "Kyle J. Temkin and Douglas H. Summerville. 2016. An Algorithmic Method for the Implantation of Detection-Resistant Covert Hardware Trojans. In Proceedings of the 11th Annual Cyber and Information Security Research Conference (CISRC ‚2016). Association for Computing Machinery, New York, NY, USA, Article 4, 1-8. DOI:https://doi.org/10.1145/2897795.2897811",
    },
    "103_sal16": {
        "ccs":"Computing Methodologies",
        "title": "Moving Least Squares Regression for High-Dimensional Stochastic Simulation Metamodeling.",
        "year": 2016,
        "scores": [1, 2, 1],
        "category": "Origin of clusters",
        "keyword": "",
        "section": "Salemi, P., Nelson, B. L., & Staum, J. (2016). Moving Least Squares Regression for High-Dimensional Stochastic Simulation Metamodeling. ACM Transactions on Modeling and Computer Simulation, 26(3), 1–25. https://doi.org/10.1145/2724708",
    },
    "104_gao17": {
        "ccs":"Computing Methodologies",
        "title": "Preference-based teaching. ",
        "year": 2017,
        "scores": [1, 2, 1],
        "category": "Origin of clusters",
        "keyword": "",
        "section": "Gao, Z., Ries, C., Simon, H. U., & Zilles, S. (2017). Preference-based teaching. Journal of Machine Learning Research: JMLR, 18(1), 1012–1043. https://dl.acm.org/doi/abs/10.5555/3122009.3122040",
    },
    "105_vla18": {
        "ccs":"Human-centered Computing",
        "title": "Infrastructuring the Solidarity Economy: Unpacking Strategies and Tactics in Designing Social Innovation. ",
        "year": 2018,
        "scores": [1, 1, 2],
        "category": "Origin of clusters",
        "keyword": "",
        "section": "Vasillis Vlachokyriakos, Clara Crivellaro, Pete Wright, and Patrick Olivier. 2018. Infrastructuring the Solidarity Economy: Unpacking Strategies and Tactics in Designing Social Innovation. In Proceedings of the 2018 CHI Conference on Human Factors in Computing Systems (CHI ’18). Association for Computing Machinery, New York, NY, USA, Paper 481, 1–12. DOI:https://doi.org/10.1145/3173574.3174055",
    },
    "106_aki18": {
        "ccs":"Computing Methodologies",
        "title": "Drift theory in continuous search spaces: expected hitting time of the (1 + 1)-ES with 1/5 success rule.",
        "year": 2018,
        "scores": [1, 2, 1],
        "category": "Origin of clusters",
        "keyword": "",
        "section": "Youhei Akimoto, Anne Auger, and Tobias Glasmachers. 2018. Drift theory in continuous search spaces: expected hitting time of the (1 + 1)-ES with 1/5 success rule. In Proceedings of the Genetic and Evolutionary Computation Conference (GECCO ’18). Association for Computing Machinery, New York, NY, USA, 801–808. DOI:https://doi.org/10.1145/3205455.3205606",
    }

}